### ISSUE TITLE
Issue when creating Hubs-Cloud since public AWS access rights changed 

### ISSUE THREAD

**Issue by Decode1415** [mozilla/hubs-cloud#314]
We already have 2 instances of Hubs-Cloud working.I want to create a another one. In order to use the new AWS settings on public access on S3 Bucket, I followed these instructions : https://github.com/mozilla/hubs/discussions/6049

To the template, I added the 3 blocks 
```
      OwnershipControls:
        Rules:
          - ObjectOwnership: ObjectWriter
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
```
on line 2810 to 2817 (${LowerStackName.Value}-assets), 2863 to 2870 (${LowerStackName.Value}-root-redirector) and 2912 to 2919 (${LowerStackName.Value}-link-redirector). And removed "AccessControl: PublicRead" that were originally on the ligne 2797, 2843 and 2885.

My modified template : https://test-mad-2023-skinny-puppy.s3.amazonaws.com/hubs-noACL.template 

Result (with terraform, but it should not change anything) : my stack is build correctly (with no error and all ressources are correct on the AWS console) but, when I look into the Asset bucket, ar first, it is empty. Then I did wait for like 2 minutes and the folders "asset" and "spoke" appeared. I compared then with the same folders from one of our working Hubs and they appears to be correct, no file missing. But, the "hubs" folder is missing. 

I am not able (yet, at least) to find why the hubs folder is not copied on the Asset bucket as it should. Also, for testing purpose and in desperation, I did try to simply copy this hubs folder from one of our working Hubs environment to our new one, with no success, the Hubs is not loading properly.

Result on our home page : 
`Missing file admin.html. Please try again.`

![Screenshot at 2023-04-27 17-04-16](https://user-images.githubusercontent.com/115099336/236025366-17248fe4-5b95-4e03-80e1-99aac7950b71.png)
